Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/radhey/editorialsnow.com/editorialsnow/scripts/scrapers/scarp_indianexpress.py", line 2, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/radhey/editorialsnow.com/editorialsnow/scripts/scrapers/scarp_indianexpress.py", line 47, in <module>
    crawlIndianExpress()
  File "/home/radhey/editorialsnow.com/editorialsnow/scripts/scrapers/scarp_indianexpress.py", line 44, in crawlIndianExpress
    for x in url_list:
TypeError: 'NoneType' object is not iterable
(1267, "Illegal mix of collations (utf8_general_ci,COERCIBLE) and (latin1_swedish_ci,IMPLICIT) for operation '='")
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/radhey/editorialsnow.com/editorialsnow/scripts/scrapers/scarp_indianexpress.py", line 53, in <module>
    crawlIndianExpress()
  File "/home/radhey/editorialsnow.com/editorialsnow/scripts/scrapers/scarp_indianexpress.py", line 48, in crawlIndianExpress
    url_list = database.filterOutExistingURL(url_list)
NameError: name 'database' is not defined
